version: '3.7'

services:
    gateway:
        depends_on:
            - encryption
        image: gateway
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=44363
            - ASPNETCORE_Kestrel__Certificates__Default__Password=password
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        ports:
            - 54218:80
            - 44363:443
        build:
            context: .
            dockerfile: HiMum.ApiGateway/Dockerfile
        volumes:
            - ./Certificates:/https:ro

    encryption:
        image: encryption
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=44325
            - ASPNETCORE_Kestrel__Certificates__Default__Password=password
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
            - Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
            - Kestrel__Certificates__Default__Password=password
        ports:
            - 21536:80
            - 44325:443
        build:
            context: .
            dockerfile: HiMum.EncryptionService/Dockerfile
        volumes:
            - ./Certificates:/https:ro